# Generated by Django 2.1.7 on 2019-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6)),
                ('identifyid', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
