# Generated by Django 2.1.7 on 2019-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190326_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='identifyid',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
